### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by lxneng** [akane10/gtrend-api#1]
Hi, @akane10 

I've successfully run the service locally, but when I request `/` it does not respond correctly and returns `500 Internal Server Error`, what's wrong with it?

```
(py3) wing@ecs-200d:~$ http http://localhost:8001
HTTP/1.1 500 Internal Server Error
Date: Tue, 30 Mar 2021 04:02:31 GMT
Transfer-Encoding: chunked
```

FULL BACKTRACE LOGS
```
(py3) wing@ecs-200d:~/gtrend-api$ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 1.41s
     Running `target/debug/gtrend-api`
🔧 Configured for development.
    => address: localhost
    => port: 8001
    => log: normal
    => workers: 4
    => secret key: generated
    => limits: forms = 32KiB
    => keep-alive: 5s
    => read timeout: 5s
    => write timeout: 5s
    => tls: disabled
🛰  Mounting /:
    => GET / (repo_index)
🛰  Mounting /repositories:
    => GET /repositories (repo_index)
    => GET /repositories?<language>&<since>&<spoken_language_code> (repo_repositories)
🛰  Mounting /developers:
    => GET /developers?<language>&<since> (developers)
🛰  Mounting /languages:
    => GET /languages (languages)
🛰  Mounting /spoken_languages:
    => GET /spoken_languages (spoken_languages)
👾 Catchers:
    => 404
    => 500
🚀 Rocket has launched from http://localhost:8001
GET /:
    => Matched: GET / (repo_index)
thread '<unnamed>' panicked at 'not currently running on the Tokio runtime.', /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:118:28
stack backtrace:
   0:     0x564ff17d6a80 - std::backtrace_rs::backtrace::libunwind::trace::h4dee703919bfd40a
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x564ff17d6a80 - std::backtrace_rs::backtrace::trace_unsynchronized::h457e839f1a563e20
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564ff17d6a80 - std::sys_common::backtrace::_print_fmt::h86a55fb30f8393c8
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x564ff17d6a80 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7b3d6cac46d277e1
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x564ff17f571f - core::fmt::write::h127419eb46f2ecc9
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/fmt/mod.rs:1092:17
   5:     0x564ff17d0185 - std::io::Write::write_fmt::h6010cfbb4726588b
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/io/mod.rs:1578:15
   6:     0x564ff17d8a2b - std::sys_common::backtrace::_print::h79b4f9652330cc9d
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x564ff17d8a2b - std::sys_common::backtrace::print::h330bb326a76af8cf
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x564ff17d8a2b - std::panicking::default_hook::{{closure}}::heb6a42a7d50a472e
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:208:50
   9:     0x564ff17d84f3 - std::panicking::default_hook::h17e521ba6d68d6e1
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:225:9
  10:     0x564ff17d8fdd - std::panicking::rust_panic_with_hook::h70db735e3a6e70cb
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:591:17
  11:     0x564ff17d8bd7 - std::panicking::begin_panic_handler::{{closure}}::h777c71c8e5a7e25c
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:497:13
  12:     0x564ff17d6f3c - std::sys_common::backtrace::__rust_end_short_backtrace::h3e9bf30168899554
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x564ff17d8b39 - rust_begin_unwind
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
  14:     0x564ff0f138c1 - core::panicking::panic_fmt::h5322a082d19786c3
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:92:14
  15:     0x564ff0f13723 - core::option::expect_failed::ha46361805fef8730
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/option.rs:1321:5
  16:     0x564ff1366867 - core::option::Option<T>::expect::h8783962e233166c5
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/option.rs:349:21
  17:     0x564ff139bee9 - tokio::runtime::handle::Handle::current::haf3debc62a07bba4
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:118:9
  18:     0x564ff1262fc2 - tokio::runtime::blocking::pool::spawn_blocking::h92249d520fb6cb58
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/blocking/pool.rs:65:14
  19:     0x564ff126c199 - tokio::task::blocking::spawn_blocking::h39cac2327105019f
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/blocking.rs:130:9
  20:     0x564ff127f0ce - <hyper::client::connect::dns::GaiResolver as tower_service::Service<hyper::client::connect::dns::Name>>::call::h7d1bd649f8022f68
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/client/connect/dns.rs:120:24
  21:     0x564ff102847e - <S as hyper::client::connect::dns::sealed::Resolve>::resolve::h11962b74d948f3aa
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/client/connect/dns.rs:338:13
  22:     0x564ff1026081 - hyper::client::connect::dns::resolve::{{closure}}::hb1888ef674c26fb5
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/client/connect/dns.rs:348:5
  23:     0x564ff1167585 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h190d13b8cd3a4caf
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  24:     0x564ff1112f89 - hyper::client::connect::http::HttpConnector<R>::call_async::{{closure}}::h52706714a643bcf7
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/client/connect/http.rs:306:25
  25:     0x564ff1167b35 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3c4f1679330a679f
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  26:     0x564ff10fe75e - <hyper::client::connect::http::HttpConnector<R> as tower_service::Service<http::uri::Uri>>::call::{{closure}}::h5c0a05ff7b81349c
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/client/connect/http.rs:247:40
  27:     0x564ff1167d35 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h776c25494ffc529f
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  28:     0x564ff109d869 - <core::pin::Pin<P> as core::future::future::Future>::poll::hb638c9dca689e9e7
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/future.rs:119:9
  29:     0x564ff10fe4a8 - <hyper::client::connect::http::HttpConnecting<R> as core::future::future::Future>::poll::h03d1ffdc530c8a40
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/client/connect/http.rs:387:9
  30:     0x564ff11430e1 - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::h68ca617a8a92319c
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/future/either.rs:63:36
  31:     0x564ff100b25e - <hyper_tls::client::HttpsConnector<T> as tower_service::Service<http::uri::Uri>>::call::{{closure}}::h5bb821ad592dc9ca
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-tls-0.4.3/src/client.rs:127:23
  32:     0x564ff1168313 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha2183e60f168555d
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  33:     0x564ff109d769 - <core::pin::Pin<P> as core::future::future::Future>::poll::h58246e2f4756da64
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/future.rs:119:9
  34:     0x564ff102c3a0 - <hyper_tls::client::HttpsConnecting<T> as core::future::future::Future>::poll::he98f94ed6f03017d
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-tls-0.4.3/src/client.rs:156:9
  35:     0x564ff116b981 - reqwest::connect::Connector::connect_with_maybe_proxy::{{closure}}::h3d32af39d98f5c3a
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/connect.rs:346:26
  36:     0x564ff1167783 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h2ac2818afe59e6a9
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  37:     0x564ff116ef7c - reqwest::connect::with_timeout::{{closure}}::h9fb0e0b431bfcfc1
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/connect.rs:500:9
  38:     0x564ff11679e3 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h34e9731d065bd393
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  39:     0x564ff109d8f9 - <core::pin::Pin<P> as core::future::future::Future>::poll::hb72e00a54f183313
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/future.rs:119:9
  40:     0x564ff1166fc6 - <hyper::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll::hdde6ed011a0ea709
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/service/oneshot.rs:50:28
  41:     0x564ff116284b - <F as futures_core::future::TryFuture>::try_poll::hfc4aa3ec44096c1c
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.6/src/future.rs:83:9
  42:     0x564ff1172318 - <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll::hc44ce76627dafe2d
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/future/try_future/into_future.rs:31:9
  43:     0x564ff1154fe7 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h707e9968b47682f7
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/future/future/map.rs:49:37
  44:     0x564ff105c0e8 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::hb6ff7dfd60388c33
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/lib.rs:111:13
  45:     0x564ff100ac48 - <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll::h670030d618fd93cd
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/lib.rs:111:13
  46:     0x564ff1017f9b - <F as futures_core::future::TryFuture>::try_poll::ha649341d081379e6
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.6/src/future.rs:83:9
  47:     0x564ff1172258 - <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll::hb6397ecdb8469951
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/future/try_future/into_future.rs:31:9
  48:     0x564ff115396a - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h19f44e82e1b44d2c
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/future/future/map.rs:49:37
  49:     0x564ff105bf68 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h75abebb66413f942
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/lib.rs:111:13
  50:     0x564ff100aa28 - <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll::hfc57a87092be6c07
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/lib.rs:111:13
  51:     0x564ff1017eab - <F as futures_core::future::TryFuture>::try_poll::h575a199ef1e8f01f
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.6/src/future.rs:83:9
  52:     0x564ff100eb2f - <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll::hb0ef81d585df61ea
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/future/try_future/try_flatten.rs:45:34
  53:     0x564ff100bc28 - <futures_util::future::try_future::TryFlatten<Fut1,Fut2> as core::future::future::Future>::poll::hd2d34a04ae46f999
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/lib.rs:111:13
  54:     0x564ff100bd48 - <futures_util::future::try_future::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll::hb1c50dda0daffd6f
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/lib.rs:111:13
  55:     0x564ff1142e11 - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::h0312cec7fe25b0cd
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/future/either.rs:63:36
  56:     0x564ff1122b93 - <hyper::common::lazy::Lazy<F,R> as core::future::future::Future>::poll::hf2140e674ea2ab33
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/common/lazy.rs:59:27
  57:     0x564ff10fea69 - futures_util::future::future::FutureExt::poll_unpin::h59900771662034eb
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/future/future/mod.rs:561:9
  58:     0x564ff102d03c - <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll::h8445e79c20cb3b2d
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/future/select.rs:92:36
  59:     0x564ff1155dda - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::ha7a69ca9692efa0e
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/future/future/map.rs:49:37
  60:     0x564ff105bc08 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h13f7fb1a6494593c
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/lib.rs:111:13
  61:     0x564ff10346b6 - <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll::hecc8ba9ba3e316ee
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/future/future/flatten.rs:45:36
  62:     0x564ff1031ed8 - <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll::h039716824d554d07
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/lib.rs:111:13
  63:     0x564ff104f7eb - <F as futures_core::future::TryFuture>::try_poll::h22ee4e48d6325bf6
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.6/src/future.rs:83:9
  64:     0x564ff11723d8 - <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll::hd676fca5d08aa419
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/future/try_future/into_future.rs:31:9
  65:     0x564ff1156b2a - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hdd304bc1340299e6
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/future/future/map.rs:49:37
  66:     0x564ff105bf08 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h6bda0c9a57ada365
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/lib.rs:111:13
  67:     0x564ff100a848 - <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll::h139090ffd9683c1f
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/lib.rs:111:13
  68:     0x564ff1017f0b - <F as futures_core::future::TryFuture>::try_poll::h8c1035a47888a916
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.6/src/future.rs:83:9
  69:     0x564ff100e3ed - <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll::h121504da9192fe8f
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/future/try_future/try_flatten.rs:45:34
  70:     0x564ff100bb68 - <futures_util::future::try_future::TryFlatten<Fut1,Fut2> as core::future::future::Future>::poll::hc3afb9e0ce40d8cb
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/lib.rs:111:13
  71:     0x564ff100bc88 - <futures_util::future::try_future::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll::h2fb08ddb2e48af27
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/lib.rs:111:13
  72:     0x564ff11c4664 - hyper::client::Client<C,B>::retryably_send_request::{{closure}}::h75ee399324ae17b9
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/client/mod.rs:255:26
  73:     0x564ff10d3f3a - <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h5df1f19ce1fa6740
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/future/poll_fn.rs:54:9
  74:     0x564ff126cc09 - <core::pin::Pin<P> as core::future::future::Future>::poll::hc92ddd40c2cdd014
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/future.rs:119:9
  75:     0x564ff1271120 - <hyper::client::ResponseFuture as core::future::future::Future>::poll::h8d06972e8f840686
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/client/mod.rs:627:9
  76:     0x564ff10fb51c - <reqwest::async_impl::client::PendingRequest as core::future::future::Future>::poll::h87e9b1d0cf110555
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/async_impl/client.rs:1318:29
  77:     0x564ff10fb161 - <reqwest::async_impl::client::Pending as core::future::future::Future>::poll::h24d812276ae7f0cb
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/async_impl/client.rs:1297:51
  78:     0x564ff0f45659 - reqwest::get::{{closure}}::h94d586a8b3f5ac35
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/lib.rs:249:5
  79:     0x564ff0f38a0b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb191e8d9c9343548
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  80:     0x564ff0f3bd0e - gtrend::fetch_html::{{closure}}::h28344f64a741b2e8
                               at /home/wing/.cargo/git/checkouts/gtrend-d0bd7bfeb3b285c6/8adc87b/src/lib.rs:86:16
  81:     0x564ff0f38c15 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he6777d544f424bb0
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  82:     0x564ff0f1e22e - gtrend::repos::Builder::get_data::{{closure}}::hf396f958465544ab
                               at /home/wing/.cargo/git/checkouts/gtrend-d0bd7bfeb3b285c6/8adc87b/src/repos.rs:105:9
  83:     0x564ff0f38135 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h404dcf3e879a66b7
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  84:     0x564ff0f254e1 - gtrend_api::routes::repo::repo_index::{{closure}}::h9d673e0f9fcb47af
                               at /home/wing/gtrend-api/src/routes/repo.rs:38:24
  85:     0x564ff0f387fa - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h89973248aea86db0
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  86:     0x564ff0f401ce - tokio::park::thread::CachedParkThread::block_on::{{closure}}::h62f88b0aaedb5ad3
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/park/thread.rs:263:54
  87:     0x564ff0f43d7d - tokio::coop::with_budget::{{closure}}::h1f35a14b1d983953
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/coop.rs:106:9
  88:     0x564ff0f2d4dd - std::thread::local::LocalKey<T>::try_with::hdce404ce58e2a9fb
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/thread/local.rs:272:16
  89:     0x564ff0f2be52 - std::thread::local::LocalKey<T>::with::h519c2c204a909235
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/thread/local.rs:248:9
  90:     0x564ff0f3e60c - tokio::coop::with_budget::hc04c7fa30539b221
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/coop.rs:99:5
  91:     0x564ff0f3e60c - tokio::coop::budget::h432f995335811046
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/coop.rs:76:5
  92:     0x564ff0f3e60c - tokio::park::thread::CachedParkThread::block_on::h5d27c4d8bf0c2458
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/park/thread.rs:263:31
  93:     0x564ff0f32de7 - tokio::runtime::enter::Enter::block_on::h5a7148867216236d
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/enter.rs:151:13
  94:     0x564ff0f412c1 - tokio::runtime::thread_pool::ThreadPool::block_on::hea75bef1a9db0fe5
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/thread_pool/mod.rs:71:9
  95:     0x564ff0f27963 - tokio::runtime::Runtime::block_on::hc30afaf035c2b591
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/mod.rs:452:43
  96:     0x564ff0f15dfc - gtrend_api::routes::repo::repo_index::h9f6db463e33064bf
                               at /home/wing/gtrend-api/src/routes/repo.rs:31:1
  97:     0x564ff0f15c80 - gtrend_api::routes::repo::rocket_route_fn_repo_index::hd3245f4b817f3da2
                               at /home/wing/gtrend-api/src/routes/repo.rs:32:14
  98:     0x564ff158bc30 - core::ops::function::Fn::call::h1974f441985d3870
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/ops/function.rs:70:5
  99:     0x564ff15e31bd - <F as rocket::handler::Handler>::handle::hca8f1be124d30796
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.7/src/handler.rs:177:9
 100:     0x564ff15a9afe - rocket::rocket::Rocket::route::he6d6d2faac1dfbed
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.7/src/rocket.rs:299:27
 101:     0x564ff15a8f27 - rocket::rocket::Rocket::route_and_process::h60ae62338358fd7d
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.7/src/rocket.rs:245:34
 102:     0x564ff15a85d0 - rocket::rocket::Rocket::dispatch::hc4da36ad8d0f4f50
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.7/src/rocket.rs:220:28
 103:     0x564ff15a5845 - <rocket::rocket::Rocket as hyper::server::Handler>::handle::h9db0a41c387c60e9
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.7/src/rocket.rs:82:24
 104:     0x564ff15d343a - hyper::server::Worker<H>::keep_alive_loop::h3c81c68973a48dc1
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/mod.rs:340:13
 105:     0x564ff15d3ed4 - hyper::server::Worker<H>::handle_connection::h3550789c1bb60ff3
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/mod.rs:282:15
 106:     0x564ff15d510b - hyper::server::handle::{{closure}}::h271f6b47907c3838
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/mod.rs:242:34
 107:     0x564ff152f550 - hyper::server::listener::spawn_with::{{closure}}::h8497bfb948b53909
                               at /home/wing/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/listener.rs:50:31
 108:     0x564ff15cecfd - std::sys_common::backtrace::__rust_begin_short_backtrace::h1b6b07d90ba2e836
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:125:18
 109:     0x564ff15572d1 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hf8947cade3110725
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/thread/mod.rs:474:17
 110:     0x564ff1555481 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha5743b6e7252b3a5
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:344:9
 111:     0x564ff152db9c - std::panicking::try::do_call::h745a370cf7515bb9
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:379:40
 112:     0x564ff15428dd - __rust_try
 113:     0x564ff152d971 - std::panicking::try::h0a77380ece3ba555
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:343:19
 114:     0x564ff15559c1 - std::panic::catch_unwind::h2ea18662984d3782
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:431:14
 115:     0x564ff1557095 - std::thread::Builder::spawn_unchecked::{{closure}}::ha8f36e6f0b315403
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/thread/mod.rs:473:30
 116:     0x564ff158bf8f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1272ea58f170b21d
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/ops/function.rs:227:5
 117:     0x564ff17dc2c3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7f7bdfc757a1add0
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/alloc/src/boxed.rs:1546:9
 118:     0x564ff17dc2c3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha294ad0fb99e9b3a
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/alloc/src/boxed.rs:1546:9
 119:     0x564ff17dc2c3 - std::sys::unix::thread::Thread::new::thread_start::h4614854ae73cd6b0
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys/unix/thread.rs:71:17
 120:     0x7f8bb49dafa3 - start_thread
 121:     0x7f8bb47814cf - clone
 122:                0x0 - <unknown>
```

**Comment by akane10** [comment]
I'm sorry, it happened when i updated tokio version. Try to get a new one, it is fixed.

**Comment by lxneng** [comment]
Cool! It works.

Thanks!
